/* ESI Quiz Studio UX V6 — information architecture + guided builder */
(function(){'use strict';
const C={
  css:`
  .esi-v6-guide{display:grid;grid-template-columns:repeat(5,1fr);gap:6px;margin:10px 0 12px}
  .esi-v6-step{min-width:0;background:#09203c;border:1px solid #21466f;border-radius:12px;padding:9px 8px;text-align:left;cursor:pointer}
  .esi-v6-step b{display:block;color:#f6c800;font-size:8px}.esi-v6-step span{display:block;color:#8fa8ca;font-size:7px;margin-top:2px;line-height:1.35}.esi-v6-step.active{border-color:#1684e8;background:#0d3159;box-shadow:0 0 0 1px #1684e844 inset}
  .esi-v6-breadcrumb{display:flex;align-items:center;gap:6px;overflow:auto;white-space:nowrap;padding:4px 1px 9px;color:#8fa8ca;font-size:7px;font-weight:800}.esi-v6-breadcrumb b{color:#fff}.esi-v6-breadcrumb i{font-style:normal;color:#31547f}
  .esi-v6-type-search{margin:0 0 8px}.esi-v6-type-search input{width:100%;background:#091f3b;color:#fff;border:1px solid #244a79;border-radius:10px;padding:9px;font-size:8px;outline:0}.esi-v6-type-search input:focus{border-color:#1684e8;box-shadow:0 0 0 3px #1684e822}
  .esi-v6-group{margin:7px 0;border:1px solid #183b63;border-radius:11px;overflow:hidden;background:#071a31}.esi-v6-group>button{width:100%;display:flex;align-items:center;justify-content:space-between;padding:9px 10px;background:#0a2342;color:#dcecff;text-align:left;font-size:8px;font-weight:900}.esi-v6-group>button span{color:#8fa8ca;font-size:7px;font-weight:700}.esi-v6-group-body{padding:5px}.esi-v6-group.collapsed .esi-v6-group-body{display:none}.esi-v6-group .tool{margin:2px 0}
  .esi-v6-empty{padding:12px;text-align:center;color:#8fa8ca;font-size:8px;display:none}
  .esi-v6-section-nav{display:flex;gap:5px;overflow:auto;padding:2px 0 8px}.esi-v6-section-nav button{flex:0 0 auto;background:#0c2749;border:1px solid #244a79;border-radius:99px;color:#8fa8ca;padding:7px 9px;font-size:7px;font-weight:800}.esi-v6-section-nav button.active{color:#fff;border-color:#1684e8;background:#1264b72b}
  .esi-v6-command{display:flex;gap:6px;align-items:center;margin:0 0 10px;padding:9px;border:1px solid #244a79;background:#091f3b;border-radius:12px}.esi-v6-command strong{font-size:8px;color:#fff}.esi-v6-command span{font-size:7px;color:#8fa8ca;flex:1}.esi-v6-command button{background:#10294d;border:1px solid #315a88;border-radius:8px;padding:6px 8px;color:#dcecff;font-size:7px;font-weight:800}
  .esi-v6-health{display:grid;grid-template-columns:repeat(4,1fr);gap:6px;margin:8px 0}.esi-v6-health>div{background:#09203c;border:1px solid #21466f;border-radius:10px;padding:8px}.esi-v6-health b{display:block;color:#f6c800;font-size:12px}.esi-v6-health span{display:block;color:#8fa8ca;font-size:6.5px;margin-top:2px}
  .esi-v6-hide{display:none!important}
  @media(max-width:720px){.esi-v6-guide{grid-template-columns:repeat(5,minmax(100px,1fr));overflow:auto;padding-bottom:2px}.esi-v6-health{grid-template-columns:1fr 1fr}.workspace{grid-template-columns:1fr!important}.toolbox,.properties{position:static!important}.esi-v6-command{align-items:flex-start}.esi-v6-command span{line-height:1.4}}
  `,
  groups:[
    ['Basics','The essentials for standard quizzes',/multiple choice|true.?false|yes.?no|multiple select/i],
    ['Written','Text, blanks and structured answers',/short text|long.?form|essay|fill.?in|numeric|formula|code/i],
    ['Interactive','Matching, ordering and hands-on responses',/matching|ordering|ranking|drag|slider|scale|hotspot|case.?study|passage/i],
    ['Visual','Image and diagram-based questions',/image|diagram|silhouette|panorama|rotation|annotation|sketch|rebus|map|difference|occlusion|puzzle/i],
    ['Media','Audio, video and recording',/audio|video|record.?yourself|freeze.?frame|gif/i],
    ['Games & Polls','Fast, social and opinion formats',/poll|word search|crossword|jumble/i]
  ],
  steps:[['1','Setup','Title, instructions & quiz rules'],['2','Questions','Build and organize your content'],['3','Enhance','Media, sections & learning tools'],['4','Settings','Scoring, timing & access'],['5','Publish','Preview, validate & share']]
};
function q(s){return document.querySelector(s)}
function all(s){return Array.from(document.querySelectorAll(s))}
function text(el){return (el?.innerText||el?.textContent||'').replace(/\s+/g,' ').trim()}
function addStyle(){if(q('#esiUxV6Style'))return;const s=document.createElement('style');s.id='esiUxV6Style';s.textContent=C.css;document.head.appendChild(s)}
function removeLegacyNoise(){all('body *').forEach(el=>{const t=text(el);if(!t)return;if(/Novel feature registry\s*[—-]?\s*140|140 novel|innovation ideas|genuinely novel features/i.test(t)&&el.children.length<12){el.remove()}})}
function makeGuide(){if(q('#esiV6Guide'))return;const host=q('.workspace')||q('.main');if(!host)return;const guide=document.createElement('div');guide.id='esiV6Guide';guide.className='esi-v6-guide';C.steps.forEach((s,i)=>{const b=document.createElement('button');b.type='button';b.className='esi-v6-step'+(i===0?' active':'');b.dataset.step=i;b.innerHTML='<b>'+s[0]+' · '+s[1]+'</b><span>'+s[2]+'</span>';b.onclick=()=>activateStep(i);guide.appendChild(b)});host.parentNode.insertBefore(guide,host)}
function activateStep(i){all('.esi-v6-step').forEach((b,n)=>b.classList.toggle('active',n===i));const ws=q('.workspace');if(!ws)return;const toolbox=q('.toolbox'),props=q('.properties');if(i===1){toolbox?.scrollIntoView({behavior:'smooth',block:'start'})}else if(i===3){props?.scrollIntoView({behavior:'smooth',block:'start'})}else if(i===4){const btn=all('button').find(b=>/preview|publish|share/i.test(text(b)));btn?.scrollIntoView({behavior:'smooth',block:'center'})}else{ws.scrollIntoView({behavior:'smooth',block:'start'})}}
function addBreadcrumb(){if(q('#esiV6Breadcrumb'))return;const shell=q('.main')||q('.shell');if(!shell)return;const b=document.createElement('div');b.id='esiV6Breadcrumb';b.className='esi-v6-breadcrumb';b.innerHTML='<b>Quiz Studio</b><i>›</i><span>Builder</span><i>›</i><b>Workspace</b>';const first=shell.firstElementChild;shell.insertBefore(b,first)}
function organizeTypes(){const box=q('.toolbox');if(!box||q('#esiV6TypeSearch'))return;const tools=all('.toolbox .tool');if(!tools.length)return;const original=tools.slice();const search=document.createElement('div');search.id='esiV6TypeSearch';search.className='esi-v6-type-search';search.innerHTML='<input type="search" placeholder="Search question type…" aria-label="Search question type">';box.insertBefore(search,box.querySelector('h3')?.nextSibling||box.firstChild);const groups=[];C.groups.forEach(g=>{const sec=document.createElement('section');sec.className='esi-v6-group';sec.dataset.group=g[0];const head=document.createElement('button');head.type='button';head.innerHTML='<span>'+g[0]+'</span><span></span>';const body=document.createElement('div');body.className='esi-v6-group-body';sec.append(head,body);head.onclick=()=>sec.classList.toggle('collapsed');groups.push({g,sec,body});box.appendChild(sec)});const other=document.createElement('section');other.className='esi-v6-group';const oh=document.createElement('button');oh.type='button';oh.innerHTML='<span>More types</span><span></span>';const ob=document.createElement('div');ob.className='esi-v6-group-body';other.append(oh,ob);oh.onclick=()=>other.classList.toggle('collapsed');box.appendChild(other);original.forEach(tool=>{const t=text(tool);const hit=groups.find(x=>x.g[2].test(t));(hit?hit.body:ob).appendChild(tool)});function counts(){groups.forEach(x=>{const n=Array.from(x.body.querySelectorAll('.tool')).filter(e=>!e.classList.contains('esi-v6-hide')).length;x.sec.querySelector('button span:last-child').textContent=n+' types'});oh.querySelector('span:last-child').textContent=ob.querySelectorAll('.tool:not(.esi-v6-hide)').length+' types'}const input=search.querySelector('input');input.addEventListener('input',()=>{const needle=input.value.trim().toLowerCase();all('.toolbox .tool').forEach(t=>t.classList.toggle('esi-v6-hide',!!needle&&!text(t).toLowerCase().includes(needle)));all('.esi-v6-group').forEach(sec=>{const visible=sec.querySelectorAll('.tool:not(.esi-v6-hide)').length;sec.style.display=visible?'':'none';if(needle)sec.classList.remove('collapsed')});counts()});counts()}
function organizeHome(){const cards=all('.main .cards .card');if(!cards.length)return;const order=['Manual Builder','AI Studio','Question Bank','Design Studio','Media Lab','Nexus Analytics'];const rank=s=>{const i=order.findIndex(x=>s.toLowerCase().includes(x.toLowerCase()));return i<0?99:i};cards.sort((a,b)=>rank(text(a))-rank(text(b))).forEach(c=>c.parentNode?.appendChild(c));}
function addBuilderCommand(){if(q('#esiV6Command'))return;const host=q('.workspace')||q('.main');if(!host)return;const c=document.createElement('div');c.id='esiV6Command';c.className='esi-v6-command';c.innerHTML='<strong>Smart workspace</strong><span>Build in order. The Studio keeps the complex tools grouped instead of putting everything in one long list.</span><button type="button">Validate</button>';c.querySelector('button').onclick=()=>{const fn=window.ESIQuizStudioV3?.validateQuiz;if(typeof fn==='function'){const r=fn();if(window.toast)window.toast(r?.valid===false?'Fix the highlighted quiz issues':'Quiz structure looks healthy');else alert(r?.valid===false?'Fix the highlighted quiz issues':'Quiz structure looks healthy')}else{all('button').find(b=>/validate|check quiz/i.test(text(b)))?.click()}};host.parentNode.insertBefore(c,host)}
function addHealth(){if(q('#esiV6Health'))return;const host=q('.quizcover')||q('.workspace');if(!host)return;const h=document.createElement('div');h.id='esiV6Health';h.className='esi-v6-health';[['Questions',()=>all('.question').length],['Sections',()=>all('.section').length],['Media',()=>all('.media,.media-item,[data-media]').length],['Status',()=>{const n=all('.question').length;return n?'Ready':'Draft'}]].forEach(x=>{const d=document.createElement('div');d.innerHTML='<b>—</b><span>'+x[0]+'</span>';try{d.querySelector('b').textContent=x[1]()}catch(_){ }h.appendChild(d)});host.insertAdjacentElement('afterend',h)}
function simplifySidebar(){const side=q('.sidebar');if(!side||q('#esiV6SectionNav'))return;const items=all('.sidebar .navitem');if(items.length<4)return;const nav=document.createElement('div');nav.id='esiV6SectionNav';nav.className='esi-v6-section-nav';const wanted=[/home/i,/build|builder/i,/ai/i,/bank/i,/nexus/i];wanted.forEach((re,i)=>{const src=items.find(x=>re.test(text(x)));if(!src)return;const b=document.createElement('button');b.type='button';b.textContent=text(src).replace(/\s+/g,' ');b.onclick=()=>src.click();nav.appendChild(b)});side.insertBefore(nav,side.firstChild)}
function boot(){addStyle();removeLegacyNoise();addBreadcrumb();makeGuide();addBuilderCommand();organizeTypes();organizeHome();addHealth();simplifySidebar();setTimeout(()=>{removeLegacyNoise();organizeTypes();},500)}
window.ESIQuizStudioUXV6={boot,organizeTypes,activateStep};
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
})();
